lines = []
lines.append('<!DOCTYPE html>')
lines.append('<html lang="en">')
lines.append('<head>')
lines.append('<meta charset="UTF-8">')
lines.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
lines.append('<meta name="description" content="Day Zero delivers expert-curated daily safety intelligence to oil and gas companies across Africa. One real incident, root cause, lesson, and action every morning at 9AM via WhatsApp.">')
lines.append('<meta name="keywords" content="oil gas safety Nigeria, HSE daily brief Africa, safety incident lessons, zero harm daily, toolbox talk Nigeria, Day Zero, Ganiyu Shittu">')
lines.append('<meta property="og:title" content="Day Zero Daily Safety Intelligence for African Oil and Gas">')
lines.append('<meta property="og:description" content="Expert-curated daily safety briefs via WhatsApp every morning. 27 years across P&G and TotalEnergies EP Nigeria.">')
lines.append('<meta property="og:url" content="https://dayzero.energy">')
lines.append('<meta property="og:type" content="website">')
lines.append('<meta name="twitter:card" content="summary_large_image">')
lines.append('<link rel="canonical" href="https://dayzero.energy">')
lines.append('<title>Day Zero Daily Safety Intelligence for African Oil and Gas</title>')
lines.append('<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;0,900;1,700&family=Barlow:wght@300;400;500;600&family=Barlow+Condensed:wght@600;700&display=swap" rel="stylesheet">')
lines.append('<style>')
lines.append('*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}')
lines.append(':root{')
lines.append('  --ink:#06101C;--ink2:#0B1929;--red:#C41F00;')
lines.append('  --red-dim:rgba(196,31,0,0.08);--red-border:rgba(196,31,0,0.22);')
lines.append('  --amber:#D4860A;--amber-bright:#E8920A;--steel:#1A3045;')
lines.append('  --cream:#F3EFE8;--off:#F8F6F2;--white:#FFFFFF;')
lines.append('  --fog:#5A7282;--fog2:#8A9BB0;--border:#E0DDD8;--border2:#D0CCC8;')
lines.append('}')
lines.append('html{scroll-behavior:smooth}')
lines.append('body{font-family:\'Barlow\',sans-serif;background:#fff;color:#06101C;overflow-x:hidden}')
lines.append('.container{max-width:1100px;margin:0 auto;padding:0 2rem}')
lines.append('nav{position:fixed;top:0;left:0;right:0;z-index:100;padding:.9rem 2rem;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #E0DDD8;background:rgba(255,255,255,0.95);backdrop-filter:blur(12px)}')
lines.append('.nav-brand{display:flex;align-items:center;gap:10px}')
lines.append('.nav-mark{width:28px;height:28px;background:#C41F00;border-radius:3px;display:flex;align-items:center;justify-content:center}')
lines.append('.nav-mark svg{width:16px;height:16px;fill:white}')
lines.append('.nav-name{font-family:\'Barlow Condensed\',sans-serif;font-size:18px;font-weight:700;letter-spacing:0.07em;color:#06101C}')
lines.append('.nav-name span{color:#C41F00}')
lines.append('.nav-cta{background:#C41F00;color:white;border:none;padding:8px 20px;border-radius:2px;font-family:\'Barlow Condensed\',sans-serif;font-size:12px;font-weight:700;letter-spacing:0.07em;cursor:pointer;text-transform:uppercase}')
lines.append('.hero{padding:9rem 2rem 5rem;background:#fff;position:relative;border-bottom:3px solid #C41F00}')
lines.append('.hero-inner{max-width:1100px;margin:0 auto}')
lines.append('.eyebrow{display:inline-flex;align-items:center;gap:7px;background:rgba(196,31,0,0.08);border:1px solid rgba(196,31,0,0.22);padding:5px 13px;border-radius:2px;margin-bottom:1.5rem}')
lines.append('.edot{width:6px;height:6px;background:#C41F00;border-radius:50%;animation:pulse 2s infinite}')
lines.append('@keyframes pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.5;transform:scale(1.3)}}')
lines.append('.etext{font-family:\'Barlow Condensed\',sans-serif;font-size:11px;font-weight:700;letter-spacing:0.13em;text-transform:uppercase;color:#C41F00}')
lines.append('.hero-headline{font-family:\'Playfair Display\',serif;font-size:clamp(3rem,6vw,5.5rem);font-weight:900;line-height:1.0;margin-bottom:1.5rem;color:#06101C}')
lines.append('.hero-headline em{color:#C41F00;font-style:italic}')
lines.append('.hero-sub{font-size:1.1rem;font-weight:300;color:#5A7282;max-width:560px;line-height:1.8;margin-bottom:2.5rem}')
lines.append('.hero-sub strong{color:#06101C;font-weight:500}')
lines.append('.hero-actions{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:4rem}')
lines.append('.btn-primary{background:#C41F00;color:white;border:none;padding:13px 30px;border-radius:2px;font-family:\'Barlow Condensed\',sans-serif;font-size:14px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;cursor:pointer}')
lines.append('.btn-ghost{background:transparent;color:#06101C;border:1px solid #D0CCC8;padding:13px 30px;border-radius:2px;font-family:\'Barlow Condensed\',sans-serif;font-size:14px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;cursor:pointer}')
lines.append('.hero-stats{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #E0DDD8}')
lines.append('.stat-block{padding:1.25rem 1rem;border-right:1px solid #E0DDD8}')
lines.append('.stat-block:last-child{border-right:none}')
lines.append('.stat-num{font-family:\'Playfair Display\',serif;font-size:2.5rem;font-weight:700;color:#C41F00}')
lines.append('.stat-lbl{font-size:11px;color:#8A9BB0;text-transform:uppercase;letter-spacing:0.08em;margin-top:4px;font-weight:500}')
lines.append('.brief-section{padding:7rem 2rem;background:#F8F6F2}')
lines.append('.section-label{font-family:\'Barlow Condensed\',sans-serif;font-size:11px;font-weight:700;letter-spacing:0.14em;text-transform:uppercase;color:#C41F00;margin-bottom:0.75rem}')
lines.append('.section-title{font-family:\'Playfair Display\',serif;font-size:clamp(1.8rem,3.5vw,2.8rem);font-weight:700;color:#06101C;line-height:1.2;margin-bottom:1rem}')
lines.append('.section-sub{font-size:0.95rem;color:#5A7282;max-width:500px;line-height:1.8;margin-bottom:3rem}')
lines.append('.brief-split{display:grid;grid-template-columns:1fr 1fr;gap:3.5rem;align-items:start}')
lines.append('.pitch-point{display:flex;gap:14px;margin-bottom:1.5rem}')
lines.append('.pitch-icon{width:34px;height:34px;border-radius:2px;display:flex;align-items:center;justify-content:center;font-size:1rem;flex-shrink:0;background:rgba(196,31,0,0.08);border:1px solid rgba(196,31,0,0.2)}')
lines.append('.pitch-label{font-size:14px;font-weight:600;color:#06101C;margin-bottom:2px}')
lines.append('.pitch-text{font-size:13px;color:#5A7282;line-height:1.6}')
lines.append('.brief-card{background:#fff;border:1px solid #E0DDD8;border-radius:4px;overflow:hidden;box-shadow:0 4px 20px rgba(6,16,28,0.07)}')
lines.append('.brief-card-top{background:#06101C;padding:1.35rem 1.5rem}')
lines.append('.brief-chip{font-family:\'Barlow Condensed\',sans-serif;font-size:9px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#C41F00;background:rgba(196,31,0,0.14);border:1px solid rgba(196,31,0,0.3);padding:3px 9px;border-radius:2px;display:inline-block;margin-bottom:7px}')
lines.append('.brief-card-title{font-family:\'Playfair Display\',serif;font-size:1.25rem;font-weight:700;color:#fff;line-height:1.3;margin-bottom:7px}')
lines.append('.brief-tags{display:flex;gap:5px;flex-wrap:wrap}')
lines.append('.btag-r{font-size:10px;padding:3px 8px;border-radius:2px;background:rgba(196,31,0,0.2);color:#F08060;font-weight:600;font-family:\'Barlow Condensed\',sans-serif}')
lines.append('.btag-s{font-size:10px;padding:3px 8px;border-radius:2px;background:rgba(255,255,255,0.07);color:#94A3B8;font-weight:600;font-family:\'Barlow Condensed\',sans-serif}')
lines.append('.brief-body{padding:1.35rem 1.5rem;background:#fff}')
lines.append('.brief-block{border-left:3px solid #E0DDD8;padding:7px 10px;margin-bottom:7px}')
lines.append('.brief-block.red{border-color:#C41F00;background:rgba(196,31,0,0.04)}')
lines.append('.brief-block.gold{border-color:#D4860A;background:rgba(212,134,10,0.04)}')
lines.append('.brief-block.green{border-color:#1A7A4A;background:rgba(26,122,74,0.04)}')
lines.append('.brief-block-label{font-family:\'Barlow Condensed\',sans-serif;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:3px}')
lines.append('.brief-block.red .brief-block-label{color:#C41F00}')
lines.append('.brief-block.gold .brief-block-label{color:#D4860A}')
lines.append('.brief-block.green .brief-block-label{color:#1A7A4A}')
lines.append('.brief-block-text{font-size:12.5px;color:#334155;line-height:1.65}')
lines.append('.brief-action-box{background:#0B1929;border-radius:3px;padding:10px 13px;margin-top:8px;border-left:3px solid #D4860A}')
lines.append('.brief-action-label{font-family:\'Barlow Condensed\',sans-serif;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:#E8920A;margin-bottom:3px}')
lines.append('.brief-action-text{font-size:12.5px;color:rgba(255,255,255,0.9);line-height:1.55;font-weight:500}')
lines.append('.brief-curator{display:flex;align-items:center;gap:11px;padding:.9rem 1.5rem;border-top:1px solid #E0DDD8;background:#F8F6F2}')
lines.append('.cur-av{width:36px;height:36px;border-radius:50%;background:#06101C;display:flex;align-items:center;justify-content:center;font-family:\'Barlow Condensed\',sans-serif;font-size:11px;font-weight:700;color:white;flex-shrink:0}')
lines.append('.cur-name{font-size:12px;font-weight:600;color:#06101C}')
lines.append('.cur-role{font-size:10px;color:#8A9BB0;margin-top:1px}')
lines.append('.cur-voice{margin-left:auto;background:#C41F00;color:white;border:none;padding:6px 12px;border-radius:2px;font-family:\'Barlow Condensed\',sans-serif;font-size:10px;font-weight:700;text-transform:uppercase;cursor:pointer}')
lines.append('.how-section{padding:7rem 2rem;background:#fff;border-top:1px solid #E0DDD8}')
lines.append('.how-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;margin-top:3.5rem;border:1px solid #E0DDD8;border-radius:4px;overflow:hidden}')
lines.append('.how-step{padding:2.5rem 2rem;background:#fff}')
lines.append('.how-step:not(:last-child){border-right:1px solid #E0DDD8}')
lines.append('.step-num{font-family:\'Playfair Display\',serif;font-size:3.5rem;font-weight:900;color:rgba(196,31,0,0.12);line-height:1;margin-bottom:1rem}')
lines.append('.step-title{font-family:\'Barlow Condensed\',sans-serif;font-size:16px;font-weight:700;letter-spacing:0.04em;text-transform:uppercase;color:#06101C;margin-bottom:0.75rem}')
lines.append('.step-text{font-size:13.5px;color:#5A7282;line-height:1.75}')
lines.append('.pricing-section{padding:7rem 2rem;background:#F3EFE8;border-top:1px solid #E0DDD8}')
lines.append('.pricing-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:3.5rem}')
lines.append('.price-card{border:1px solid #E0DDD8;border-radius:3px;padding:1.75rem;position:relative;background:#fff}')
lines.append('.price-card.featured{border-color:#D4860A;border-width:1.5px}')
lines.append('.feat-badge{position:absolute;top:-11px;left:50%;transform:translateX(-50%);background:#D4860A;color:#412402;font-family:\'Barlow Condensed\',sans-serif;font-size:10px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;padding:4px 14px;border-radius:2px;white-space:nowrap}')
lines.append('.plan-name{font-family:\'Barlow Condensed\',sans-serif;font-size:12px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#8A9BB0;margin-bottom:1rem}')
lines.append('.plan-price{font-family:\'Playfair Display\',serif;font-size:2rem;font-weight:700;color:#06101C;margin-bottom:4px}')
lines.append('.plan-price span{font-size:13px;font-weight:400;color:#8A9BB0;font-family:\'Barlow\',sans-serif}')
lines.append('.plan-users{font-size:12px;color:#5A7282;margin-bottom:1.5rem;padding-bottom:1.25rem;border-bottom:1px solid #E0DDD8}')
lines.append('.plan-features{list-style:none;margin-bottom:1.75rem;display:flex;flex-direction:column;gap:9px}')
lines.append('.plan-features li{display:flex;gap:8px;font-size:13px;color:#475569;line-height:1.5}')
lines.append('.plan-features li::before{content:"checkmark";color:#8A9BB0;font-weight:700;flex-shrink:0;margin-top:1px}')
lines.append('.plan-btn{width:100%;padding:11px;border-radius:2px;font-family:\'Barlow Condensed\',sans-serif;font-size:12px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;cursor:pointer;border:1px solid #D0CCC8;background:transparent;color:#06101C}')
lines.append('.price-card.featured .plan-btn{background:#D4860A;color:#06101C;border-color:#D4860A}')
lines.append('.trust-strip{background:#1A3045;padding:1.5rem 2rem}')
lines.append('.trust-inner{max-width:1100px;margin:0 auto;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:14px}')
lines.append('.trust-item{display:flex;align-items:center;gap:7px;font-size:12.5px;color:rgba(255,255,255,0.6)}')
lines.append('.trust-dot{width:5px;height:5px;border-radius:50%;background:#D4860A;flex-shrink:0}')
lines.append('.curator-section{padding:7rem 2rem;background:#fff;border-top:1px solid #E0DDD8}')
lines.append('.curator-inner{display:grid;grid-template-columns:1fr 1fr;gap:5rem;align-items:center}')
lines.append('.curator-card-big{background:#06101C;border-radius:4px;padding:2.25rem;position:relative;overflow:hidden}')
lines.append('.curator-card-big::before{content:"";position:absolute;top:-40px;right:-40px;width:140px;height:140px;border-radius:50%;background:rgba(196,31,0,0.08)}')
lines.append('.curator-initials{width:60px;height:60px;border-radius:50%;background:#C41F00;display:flex;align-items:center;justify-content:center;font-family:\'Barlow Condensed\',sans-serif;font-size:20px;font-weight:700;color:white;margin-bottom:1rem}')
lines.append('.curator-fullname{font-family:\'Playfair Display\',serif;font-size:1.4rem;font-weight:700;color:white;margin-bottom:4px}')
lines.append('.curator-title{font-size:13px;color:#8A9BB0;margin-bottom:1.25rem}')
lines.append('.curator-badges{display:flex;flex-direction:column;gap:7px}')
lines.append('.cur-badge{display:flex;align-items:center;gap:10px;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);border-radius:2px;padding:8px 12px}')
lines.append('.cur-badge-icon{font-size:0.9rem;flex-shrink:0}')
lines.append('.cur-badge-text{font-size:12px;color:#A8B8CC}')
lines.append('.curator-quote{font-family:\'Playfair Display\',serif;font-size:1.05rem;font-style:italic;color:#5A7282;line-height:1.7;margin-top:1.5rem;padding-left:1.25rem;border-left:3px solid #C41F00}')
lines.append('.footer-cta{padding:6rem 2rem;background:#C41F00;text-align:center;position:relative;overflow:hidden}')
lines.append('.footer-cta::before{content:"DAY ZERO";position:absolute;font-family:\'Playfair Display\',serif;font-size:18vw;font-weight:900;color:rgba(255,255,255,0.05);left:50%;top:50%;transform:translate(-50%,-50%);white-space:nowrap;pointer-events:none}')
lines.append('.footer-cta-title{font-family:\'Playfair Display\',serif;font-size:clamp(2rem,4vw,3.2rem);font-weight:700;color:white;line-height:1.2;margin-bottom:1rem;position:relative}')
lines.append('.footer-cta-sub{color:rgba(255,255,255,0.75);font-size:1rem;line-height:1.75;max-width:480px;margin:0 auto 2.5rem;position:relative}')
lines.append('.footer-cta-btn{background:white;color:#C41F00;border:none;padding:14px 38px;border-radius:2px;font-family:\'Barlow Condensed\',sans-serif;font-size:15px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;cursor:pointer;position:relative}')
lines.append('footer{background:#06101C;padding:1.75rem 2rem}')
lines.append('.footer-inner{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px;max-width:1100px;margin:0 auto}')
lines.append('.footer-logo{font-family:\'Barlow Condensed\',sans-serif;font-size:15px;font-weight:700;color:#8A9BB0}')
lines.append('.footer-logo span{color:#E8920A}')
lines.append('.footer-note{font-size:12px;color:#2A3A4A}')
lines.append('.footer-link{font-size:12px;color:#5A7282;text-decoration:none}')
lines.append('@media(max-width:820px){.brief-split,.curator-inner,.how-grid,.pricing-grid{grid-template-columns:1fr}.hero-stats{grid-template-columns:1fr}.stat-block:not(:last-child){border-right:none;border-bottom:1px solid #E0DDD8}.trust-inner{flex-direction:column;align-items:flex-start}.how-step:not(:last-child){border-right:none;border-bottom:1px solid #E0DDD8}}')
lines.append('</style>')
lines.append('</head>')
lines.append('<body>')
lines.append('<nav>')
lines.append('  <div class="nav-brand">')
lines.append('    <div class="nav-mark"><svg viewBox="0 0 24 24"><path d="M12 2a10 10 0 100 20A10 10 0 0012 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"/></svg></div>')
lines.append('    <span class="nav-name">DAY <span>ZERO</span></span>')
lines.append('  </div>')
lines.append('  <button class="nav-cta" onclick="document.getElementById(\'subscribe\').scrollIntoView({behavior:\'smooth\'})">Get Started</button>')
lines.append('</nav>')
lines.append('<section class="hero">')
lines.append('  <div class="hero-inner">')
lines.append('    <div class="eyebrow"><span class="edot"></span><span class="etext">Daily Safety Intelligence · Oil and Gas · Africa</span></div>')
lines.append('    <h1 class="hero-headline">Every day is<br><em>Day Zero</em><br>of safety.</h1>')
lines.append('    <p class="hero-sub">One real incident. One root cause. One action delivered to your team WhatsApp every morning at 9AM. Curated by a safety professional <strong>trained at Procter and Gamble and forged across 24 years in TotalEnergies EP Nigeria upstream operations.</strong></p>')
lines.append('    <div class="hero-actions">')
lines.append('      <button class="btn-primary" onclick="document.getElementById(\'subscribe\').scrollIntoView({behavior:\'smooth\'})">Start Free Trial</button>')
lines.append('      <button class="btn-ghost" onclick="document.getElementById(\'sample\').scrollIntoView({behavior:\'smooth\'})">See Today Brief</button>')
lines.append('    </div>')
lines.append('    <div class="hero-stats">')
lines.append('      <div class="stat-block"><div class="stat-num">365</div><div class="stat-lbl">Briefs per year</div></div>')
lines.append('      <div class="stat-block"><div class="stat-num">27</div><div class="stat-lbl">Years field expertise</div></div>')
lines.append('      <div class="stat-block"><div class="stat-num">0</div><div class="stat-lbl">Days with excuses</div></div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('</section>')
lines.append('<section class="brief-section" id="sample">')
lines.append('  <div class="container">')
lines.append('    <div class="brief-split">')
lines.append('      <div>')
lines.append('        <div class="section-label">Sample Edition</div>')
lines.append('        <h2 class="section-title">What happened on this day. What it means for your team today.</h2>')
lines.append('        <p class="section-sub">Every brief is curated from a verified global incident database and filtered by 27 years of field expertise. Not generated. Not scraped. Written by a human who has spent decades inside the industry.</p>')
lines.append('        <div class="pitch-point"><div class="pitch-icon">&#128343;</div><div><div class="pitch-label">9:00 AM delivery</div><div class="pitch-text">Arrives before the morning toolbox talk. Read in 90 seconds. Discussed in five minutes.</div></div></div>')
lines.append('        <div class="pitch-point"><div class="pitch-icon">&#128241;</div><div><div class="pitch-label">WhatsApp-native</div><div class="pitch-text">No app. No login. Lives where your workers already are.</div></div></div>')
lines.append('        <div class="pitch-point"><div class="pitch-icon">&#128196;</div><div><div class="pitch-label">Compliance PDF</div><div class="pitch-text">Every brief exports as a signable PDF. 365 days of documented safety briefings is a regulatory asset.</div></div></div>')
lines.append('      </div>')
lines.append('      <div class="brief-card">')
lines.append('        <div class="brief-card-top">')
lines.append('          <span class="brief-chip">Sample Edition</span>')
lines.append('          <div class="brief-card-title">Piper Alpha: When a Permit-to-Work System Failed 167 People</div>')
lines.append('          <div class="brief-tags"><span class="btag-r">Offshore Platform</span><span class="btag-s">Process Safety 1988</span></div>')
lines.append('        </div>')
lines.append('        <div class="brief-body">')
lines.append('          <div class="brief-block red"><div class="brief-block-label">What Happened</div><div class="brief-block-text">167 men died because one conversation did not happen at shift handover. The night crew started a pump without knowing the safety valve had been removed. Nobody told them.</div></div>')
lines.append('          <div class="brief-block gold"><div class="brief-block-label">Root Cause</div><div class="brief-block-text">Suspended permit not communicated at shift handover.</div></div>')
lines.append('          <div class="brief-block green"><div class="brief-block-label">Lesson Learned</div><div class="brief-block-text">A PTW system is a communication protocol not a document.</div></div>')
lines.append('          <div class="brief-action-box"><div class="brief-action-label">Action for today</div><div class="brief-action-text">Walk your PTW board. Tell the incoming shift verbally not on paper.</div></div>')
lines.append('        </div>')
lines.append('        <div class="brief-curator">')
lines.append('          <div class="cur-av">GS</div>')
lines.append('          <div><div class="cur-name">Ganiyu Shittu</div><div class="cur-role">27 yrs P&G + TotalEnergies EP Nigeria</div></div>')
lines.append('          <button class="cur-voice">Friday Note</button>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('</section>')
lines.append('<section class="how-section">')
lines.append('  <div class="container">')
lines.append('    <div class="section-label">How It Works</div>')
lines.append('    <h2 class="section-title">Three steps. Zero friction.</h2>')
lines.append('    <div class="how-grid">')
lines.append('      <div class="how-step"><div class="step-num">01</div><div class="step-title">Subscribe your company</div><div class="step-text">Sign your annual contract. Add your team WhatsApp numbers and emails. No app installation. Your first brief arrives the next morning at 9:00 AM WAT.</div></div>')
lines.append('      <div class="how-step"><div class="step-num">02</div><div class="step-title">Receive the daily brief</div><div class="step-text">Every morning one real incident from the global oil and gas incident database, curated by Ganiyu. Root cause. Lesson. One action. Under 100 words.</div></div>')
lines.append('      <div class="how-step"><div class="step-num">03</div><div class="step-title">Run the toolbox talk</div><div class="step-text">Your HSE manager reads it at the morning briefing. Print the PDF. Sign it. File it. 365 days of documented expert-verified safety briefings NUPRC audit-ready.</div></div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('</section>')
lines.append('<section class="pricing-section" id="subscribe">')
lines.append('  <div class="container">')
lines.append('    <div class="section-label">Pricing</div>')
lines.append('    <h2 class="section-title">Annual contracts. No surprises.</h2>')
lines.append('    <p style="font-size:.95rem;color:#5A7282;line-height:1.75;margin-bottom:0">Quarterly instalments available on Operations tier and above. One discount: 20% for full annual payment on signing.</p>')
lines.append('    <div class="pricing-grid">')
lines.append('      <div class="price-card"><div class="plan-name">Field Contract</div><div class="plan-price">$3,000 <span>/ year</span></div><div class="plan-users">Up to 100 workers</div><ul class="plan-features"><li>Daily WhatsApp brief</li><li>Daily email delivery</li><li>PDF archive access</li><li>Admin dashboard</li></ul><button class="plan-btn">Get Started</button></div>')
lines.append('      <div class="price-card featured"><div class="feat-badge">Most Popular</div><div class="plan-name">Operations Contract</div><div class="plan-price">$9,600 <span>/ year</span></div><div class="plan-users">Up to 500 workers</div><ul class="plan-features"><li>Everything in Field</li><li>Friday voice note from Ganiyu</li><li>Sector-specific briefs</li><li>Monthly impact report</li><li>Compliance PDF exports</li></ul><button class="plan-btn">Get Started</button></div>')
lines.append('      <div class="price-card"><div class="plan-name">Corporate Contract</div><div class="plan-price">$24,000 <span>/ year</span></div><div class="plan-users">Unlimited workers</div><ul class="plan-features"><li>Everything in Operations</li><li>Custom company branding</li><li>Quarterly business review</li><li>Regulatory audit support</li><li>API access</li></ul><button class="plan-btn">Contact Us</button></div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('</section>')
lines.append('<div class="trust-strip">')
lines.append('  <div class="trust-inner">')
lines.append('    <div class="trust-item"><div class="trust-dot"></div>Annual contract no monthly rolling</div>')
lines.append('    <div class="trust-item"><div class="trust-dot"></div>Compliance PDF on every brief</div>')
lines.append('    <div class="trust-item"><div class="trust-dot"></div>NUPRC and DPR audit-ready records</div>')
lines.append('    <div class="trust-item"><div class="trust-dot"></div>Quarterly impact reports included</div>')
lines.append('    <div class="trust-item"><div class="trust-dot"></div>dayzero.energy</div>')
lines.append('  </div>')
lines.append('</div>')
lines.append('<section class="curator-section">')
lines.append('  <div class="container">')
lines.append('    <div class="curator-inner">')
lines.append('      <div>')
lines.append('        <div class="curator-card-big">')
lines.append('          <div class="curator-initials">GS</div>')
lines.append('          <div class="curator-fullname">Ganiyu Shittu</div>')
lines.append('          <div class="curator-title">HSE and Mechanical Engineering Professional Founder Day Zero</div>')
lines.append('          <div class="curator-badges">')
lines.append('            <div class="cur-badge"><span class="cur-badge-icon">&#127970;</span><span class="cur-badge-text">Procter and Gamble HSE foundation</span></div>')
lines.append('            <div class="cur-badge"><span class="cur-badge-icon">&#9889;</span><span class="cur-badge-text">TotalEnergies EP Nigeria 24 years upstream</span></div>')
lines.append('            <div class="cur-badge"><span class="cur-badge-icon">&#128737;</span><span class="cur-badge-text">27 years total Cross-industry safety leadership</span></div>')
lines.append('            <div class="cur-badge"><span class="cur-badge-icon">&#127757;</span><span class="cur-badge-text">West Africa upstream operations expertise</span></div>')
lines.append('          </div>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('      <div>')
lines.append('        <div class="section-label">The Curator</div>')
lines.append('        <h2 class="section-title">The editorial judgement no algorithm can replicate.</h2>')
lines.append('        <p style="font-size:.95rem;color:#5A7282;line-height:1.8;margin-bottom:1.5rem">Ganiyu Shittu brings 27 years of safety leadership across two of the world most demanding organisations Procter and Gamble where global safety systems are built and TotalEnergies EP Nigeria where they are tested daily against the realities of West African upstream operations. Day Zero draws from a verified global incident database. What makes it unique is not where the data comes from it is who selects it how it is written and the expert judgement applied to every entry.</p>')
lines.append('        <div class="curator-quote">The incident that kills people tomorrow is not yet in any database. Day Zero teaches your team to recognise what they cannot yet name.</div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('</section>')
lines.append('<section class="footer-cta">')
lines.append('  <div class="section-label" style="color:rgba(255,255,255,0.55);position:relative">Start Today</div>')
lines.append('  <div class="footer-cta-title">Your team first brief arrives tomorrow at 9:00 AM.</div>')
lines.append('  <p class="footer-cta-sub">No app. No complexity. Expert safety intelligence every morning where your team already is.</p>')
lines.append('  <button class="footer-cta-btn" onclick="document.getElementById(\'subscribe\').scrollIntoView({behavior:\'smooth\'})">Subscribe Now</button>')
lines.append('</section>')
lines.append('<footer>')
lines.append('  <div class="footer-inner">')
lines.append('    <div class="footer-logo">DAY <span>ZERO</span> An Identis Ltd Initiative</div>')
lines.append('    <div class="footer-note">2026 Day Zero Energy Limited dayzero.energy</div>')
lines.append('    <a href="https://ganiyushittu.com" class="footer-link">ganiyushittu.com</a>')
lines.append('  </div>')
lines.append('</footer>')
lines.append('<script type="application/ld+json">')
lines.append('{"@context":"https://schema.org","@type":"Organization","name":"Day Zero","url":"https://dayzero.energy","description":"Daily safety intelligence for African oil and gas companies. Expert-curated incident briefs delivered via WhatsApp every morning.","founder":{"@type":"Person","name":"Ganiyu Shittu","jobTitle":"HSE Professional and Curator","description":"27 years of safety leadership across Procter and Gamble and TotalEnergies EP Nigeria"},"areaServed":"Africa","serviceType":"Safety Intelligence"}')
lines.append('</script>')
lines.append('</body>')
lines.append('</html>')

with open('index.html', 'w') as f:
    f.write('\n'.join(lines))

print('Done written', len('\n'.join(lines)), 'bytes')
